Algoritmo "exercicio15"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   :  Le um valor e escreve se é positivo ou negativo (considerando o valor zero como positivo).
// Autor(a)    : Guilherme Miranda de Morais
// Data atual  : 8/31/2026
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um número: ")
   Leia(numero)
   se numero >= 0 entao
      Escreval("Positivo")
   senao
      Escreval("Negativo")
   fimse

Fimalgoritmo