Algoritmo "exercicio06"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa 
// Descrição   : Calcula a área do retângulo
// Autor(a)    : Guilherme Miranda de Morais
// Data atual  : 8/28/2026
Var
// Seção de Declarações das variáveis 
altura:inteiro
largura:inteiro
area:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite a ALTURA: ")
Leia(altura)
Escreva("Digite a LARGURA: ")
Leia(largura)
area<-altura * largura
Escreva("A área do retângulo é: ", area)


Fimalgoritmo