Algoritmo "exercicio14"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Le um valor e escrever a mensagem É MAIOR QUE 10! se o valor lido for maior que 10, caso contrário escreve NÃO É MAIOR QUE 10!
// Autor(a)    : Guilherme Miranda de Morais
// Data atual  : 8/31/2026
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um número: ")
   Leia(numero)
   se numero > 10 entao
      Escreval("É maior que 10")
   senao
      Escreval("É menor que 10")
   fimse

Fimalgoritmo